<a href="https://colab.research.google.com/github/Akshithkumarreddy/Machine_learning_AL/blob/main/convolution_example.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [24]:
import numpy as np

In [26]:
# Generate a random 5x5 input matrix and a 3x3 kernel
input_matrix = np.random.randint(0, 10, (5, 5))
kernel = np.random.randint(0, 10, (3, 3))

print(input_matrix)
print(kernel)

[[7 2 0 3 5]
 [9 4 4 6 4]
 [4 3 4 4 8]
 [4 3 7 5 5]
 [0 1 5 9 3]]
[[0 5 0]
 [1 2 4]
 [2 0 3]]


In [27]:
# Get dimensions
input_rows, input_cols = input_matrix.shape
kernel_size = kernel.shape[0]  # assuming square kernel
output_size = input_rows - kernel_size + 1

In [28]:
# Initialize output matrix
output = np.zeros((output_size, output_size))

In [29]:
# Perform convolution using for loops
for i in range(output_size):
    for j in range(output_size):
        region = input_matrix[i:i+kernel_size, j:j+kernel_size]
        output[i, j] = np.sum(region * kernel)

In [30]:
# Display results
print("Input Matrix:\n", input_matrix)
print("\nKernel:\n", kernel)
print("\nConvolved Output:\n", output)

Input Matrix:
 [[7 2 0 3 5]
 [9 4 4 6 4]
 [4 3 4 4 8]
 [4 3 7 5 5]
 [0 1 5 9 3]]

Kernel:
 [[0 5 0]
 [1 2 4]
 [2 0 3]]

Convolved Output:
 [[ 63.  54.  79.]
 [ 75.  68. 103.]
 [ 68.  86.  76.]]
