<a href="https://colab.research.google.com/github/Akshithkumarreddy/Machine_learning_AL/blob/main/Math_for_ML_Algebra.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np

In [2]:
a = np.array([20,40,40])
b = np.array([10,20,30])
c = np.array([5,10,15,20])

#Vector operations will be performated only if the vectors of same dimensions

In [3]:
a+b

array([30, 60, 70])

In [4]:
a+c

ValueError: operands could not be broadcast together with shapes (3,) (4,) 

In [5]:
a-b

array([10, 20, 10])

In [6]:
a-c

ValueError: operands could not be broadcast together with shapes (3,) (4,) 

In [7]:
a*b

array([ 200,  800, 1200])

In [8]:
a/b

array([2.        , 2.        , 1.33333333])

In [9]:
scalar=2

In [10]:
list_a=[10,11,12,13,14,15]
print(list_a)

[10, 11, 12, 13, 14, 15]


In [11]:
listasarray = np.array(list_a)
print(listasarray)

[10 11 12 13 14 15]


In [12]:
scalar*list_a #it prints list a scalar times

[10, 11, 12, 13, 14, 15, 10, 11, 12, 13, 14, 15]

In [13]:
scalar*listasarray # it mutiples each scaler into list as array elements

array([20, 22, 24, 26, 28, 30])

#dot product of vectors

a.b = sum of a*b #it shoud be same dimensional

In [18]:
import numpy as np
a = np.array([1,2,3,4,5])
b = np.array([6,7,8,9,10])

In [19]:
np.dot(a,b) # 1*6 + 2*7 + 3*8 + 4*9 + 5*10 => 6 + 14 + 24 +  36 + 50 => 130

130

Basic properties for DOT product

1. it is commutative a.b = b.a
2. it is distributive i.e.; a(b+c) = a.b + a.c

In [20]:
c = np.array([11,12,13,14,15])

In [21]:
np.dot(b,a)

130

In [23]:
first_result = np.dot(a,b+c)
print(first_result)

335


In [24]:
second_result = np.dot(a,b) + np.dot(a,c)
print(second_result)

335


Magnitude of a vector: it is the distance between Tail to Head of a vector

formula : squareroot of sum of squared vector elements

in numpy we have a function called norm which takes care of this calculation

magnitude = np.norm(a) # if we need to calculate magnitude of vector a


Vector projection : A vector projection of a vector a onto vector b is called orthogonal projection of a onto b

Formula : Take the dot product of vector b and a , and divide it by magnitude of a

it gives scalar value

in order to get vector projection, we need to multiply the scalar value with unit factor of b

Scalar and vector projection

In [25]:
import numpy as np
from numpy import linalg as lng

In [26]:
a = np.array([10,20,30,40,50])
b = np.array([60,70,80,90,100])

In [27]:
lng.norm(a)

74.16198487095663

In [28]:
vector_projection = (np.dot(a,b)/np.dot(b,b))*b

In [29]:
print(vector_projection)

[23.63636364 27.57575758 31.51515152 35.45454545 39.39393939]


Three properties of vecators -

1. are Linearlly independet of each other
2. span the whole space
3. aren't unique